services:
  catalogdb:
    image: postgres

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile
    # args:
    #   - configuration=Debug

  basketdb:
    image: postgres

  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: BasketApi/Dockerfile

  discountgrpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: DiscountGrpc/Dockerfile

  orderdb:
    image: mcr.microsoft.com/mssql/server

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq:management

# volumes:
#   postgres_catalog:
